apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpwebserver
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: yenaing/php72
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvol
          mountPath: /var/www/html/
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: hhhpvc
---
apiVersion: v1
kind: Service
metadata:
  name: phpservice
  labels:
    run: phpservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: php
