apiVersion: v1
kind: PersistentVolume
metadata:
  # any PV name
  name: hhhpv
spec:
  storageClassName: hhh002
  capacity:
    # storage size
    storage: 10Gi
  accessModes:
    # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    # retain even if pods terminate
    Retain
  nfs:
    # NFS server's definition
    path: /mnt/nhn/data
    server: 192.168.14.10
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: hhhpvc
spec:
  storageClassName: hhh002
  accessModes:
  # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  resources:
    requests:
       # storage size to use
      storage: 5Gi
